
package parser;

import parser.PositionalArg;
import parser.TokenArg;

/**
 * Define valid command line arguments here
 */
public final class Args {
	public static enum Tag {
		III_DIR("iii_dir"), REFRESH("refresh"), FORCE("force"), QUIET("quiet"), VERBOSE("verbose"),
		EXTRA_VERBOSE("extra_verbose"), HELP("help"), INPUT_DCP("input_dcp"), OUTPUT_DCP("output_dcp");

		String tag;

		Tag(String str) {
			tag = str;
		}

		@Override
		public String toString() {
			return tag;
		}
	}

	static final String[] HELP_SWITCH = { "-h", "--help" };

	// used {d, f, h, q, r, Vv}
	static final TokenArg[] TOKEN_LIST = {
			new TokenArg(Tag.III_DIR.toString(), new String[] { "-d", "--iii_dir" }, new String[] { "iii_dir" },
					new boolean[] { true }, "The directory in which to store partially built designs."),
			new TokenArg(Tag.REFRESH.toString(), new String[] { "-r", "--refresh" },
					"Force recompilation from input dcp. Ignore any intermediate designs."),
			new TokenArg(Tag.FORCE.toString(), new String[] { "-f", "--force" },
					"Force overwrite of output files (intermediate files in .iii are always overwritten)."),
			new TokenArg(Tag.QUIET.toString(), new String[] { "-q", "--quiet" },
					"Display less progress information. Run Vivado tcl commands with '-quiet' flag."),
			new TokenArg(Tag.VERBOSE.toString(), new String[] { "-v", "--verbose" },
					"Display extra progress information (ignored if also quiet)."),
			new TokenArg(Tag.EXTRA_VERBOSE.toString(), new String[] { "-V", "--extra_verbose" },
					"Display extra progress information (ignored if also quiet). Run Vivado tcl commands with '-verbose' flag."),
			new TokenArg(Tag.HELP.toString(), HELP_SWITCH, "Print this help message and exit.")
	};

	static final PositionalArg[] POSITIONAL_ARGS = {
			new PositionalArg(Tag.INPUT_DCP.toString(), true,
					"Original design checkpoint file generated by Vivado in '<project_name>.runs/impl_1/<design_name>_wrapper_routed.dcp'."),
			new PositionalArg(Tag.OUTPUT_DCP.toString(), true,
					"Name to give final output design.")
	};
}